/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


/**
 *
 * @author LENOVO
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(255,255,255));
        jPanel1.setBackground(new java.awt.Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TxtNum1 = new javax.swing.JTextField();
        TxtNum2 = new javax.swing.JTextField();
        RadioButtonRadianes = new javax.swing.JRadioButton();
        RadioButtonRadianes1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        BtnCoseno = new javax.swing.JButton();
        BtnSeno = new javax.swing.JButton();
        BtnTangente = new javax.swing.JButton();
        BtnMC = new javax.swing.JButton();
        BtnMR = new javax.swing.JButton();
        BtnMS = new javax.swing.JButton();
        BtnMmas = new javax.swing.JButton();
        BtnMmenos = new javax.swing.JButton();
        BtnCosmenos1 = new javax.swing.JButton();
        BtnSenmenos1 = new javax.swing.JButton();
        BtnTanmenos1 = new javax.swing.JButton();
        BtnBackSpace = new javax.swing.JButton();
        BtnCE = new javax.swing.JButton();
        BtnMasMenos = new javax.swing.JButton();
        BtnRaiz = new javax.swing.JButton();
        BtnC = new javax.swing.JButton();
        BtnPi = new javax.swing.JButton();
        BtnXaMenos1 = new javax.swing.JButton();
        BntXmenosY = new javax.swing.JButton();
        BtnNum7 = new javax.swing.JButton();
        BtnSlash = new javax.swing.JButton();
        BtnPorcentaje = new javax.swing.JButton();
        BtnNum8 = new javax.swing.JButton();
        BtnNum9 = new javax.swing.JButton();
        BtnEuler = new javax.swing.JButton();
        BtnY_RaizdeX = new javax.swing.JButton();
        BtnXalCubo = new javax.swing.JButton();
        BtnNum4 = new javax.swing.JButton();
        BtnNum5 = new javax.swing.JButton();
        BtnNum6 = new javax.swing.JButton();
        BtnMultiplicar = new javax.swing.JButton();
        Btn1entreX = new javax.swing.JButton();
        BtnRestar = new javax.swing.JButton();
        BtnNum3 = new javax.swing.JButton();
        BtnNum2 = new javax.swing.JButton();
        BtnNum1 = new javax.swing.JButton();
        BtnXalCuadrado = new javax.swing.JButton();
        BtnRaizCubica = new javax.swing.JButton();
        BtnFactorial = new javax.swing.JButton();
        Btn10a_laX = new javax.swing.JButton();
        BtnEXP = new javax.swing.JButton();
        BtnLogaritmo = new javax.swing.JButton();
        BtnNum0 = new javax.swing.JButton();
        BtnPuntoDecimal = new javax.swing.JButton();
        BtnSumar = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        ComboxFuncionesPredeterminadas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BDJ Quantum");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(20, 20, 20, 20));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("JFramePrincipal"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtNum1.setBorder(null);
        TxtNum1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        getContentPane().add(TxtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 450, 32));

        TxtNum2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtNum2.setText("0");
        TxtNum2.setBorder(null);
        TxtNum2.setMargin(new java.awt.Insets(10, 10, 10, 10));
        getContentPane().add(TxtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 450, 30));

        RadioButtonRadianes.setText("Sexagesimales");
        RadioButtonRadianes.setBorder(null);
        RadioButtonRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonRadianesActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButtonRadianes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        RadioButtonRadianes1.setText("Radianes");
        RadioButtonRadianes1.setBorder(null);
        getContentPane().add(RadioButtonRadianes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        BtnCoseno.setText("cos");
        BtnCoseno.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnSeno.setText("sen");
        BtnSeno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSenoActionPerformed(evt);
            }
        });

        BtnTangente.setText("tan");
        BtnTangente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTangenteActionPerformed(evt);
            }
        });

        BtnMC.setText("MC");
        BtnMC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMCActionPerformed(evt);
            }
        });

        BtnMR.setText("MR");
        BtnMR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMRActionPerformed(evt);
            }
        });

        BtnMS.setText("MS");
        BtnMS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMSActionPerformed(evt);
            }
        });

        BtnMmas.setText("M+");
        BtnMmas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMmasActionPerformed(evt);
            }
        });

        BtnMmenos.setText("M-");
        BtnMmenos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMmenosActionPerformed(evt);
            }
        });

        BtnCosmenos1.setText("cos-1");
        BtnCosmenos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnSenmenos1.setText("sen-1");
        BtnSenmenos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnSenmenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSenmenos1ActionPerformed(evt);
            }
        });

        BtnTanmenos1.setText("tan-1");
        BtnTanmenos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnTanmenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTanmenos1ActionPerformed(evt);
            }
        });

        BtnBackSpace.setText("<---");
        BtnBackSpace.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackSpaceActionPerformed(evt);
            }
        });

        BtnCE.setForeground(new java.awt.Color(255, 102, 51));
        BtnCE.setText("CE");
        BtnCE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCEActionPerformed(evt);
            }
        });

        BtnMasMenos.setText("±");
        BtnMasMenos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMasMenosActionPerformed(evt);
            }
        });

        BtnRaiz.setText("√");
        BtnRaiz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRaizActionPerformed(evt);
            }
        });

        BtnC.setForeground(new java.awt.Color(255, 102, 51));
        BtnC.setText("C");
        BtnC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCActionPerformed(evt);
            }
        });

        BtnPi.setText("π");
        BtnPi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPiActionPerformed(evt);
            }
        });

        BtnXaMenos1.setText("x^-1");
        BtnXaMenos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnXaMenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXaMenos1ActionPerformed(evt);
            }
        });

        BntXmenosY.setText("x^y");
        BntXmenosY.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BntXmenosY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntXmenosYActionPerformed(evt);
            }
        });

        BtnNum7.setText("7");
        BtnNum7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum7ActionPerformed(evt);
            }
        });

        BtnSlash.setText("/");
        BtnSlash.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnSlash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSlashActionPerformed(evt);
            }
        });

        BtnPorcentaje.setText("%");
        BtnPorcentaje.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPorcentajeActionPerformed(evt);
            }
        });

        BtnNum8.setText("8");
        BtnNum8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum8ActionPerformed(evt);
            }
        });

        BtnNum9.setText("9");
        BtnNum9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum9ActionPerformed(evt);
            }
        });

        BtnEuler.setText("e");
        BtnEuler.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEulerActionPerformed(evt);
            }
        });

        BtnY_RaizdeX.setText("y√x");
        BtnY_RaizdeX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnY_RaizdeX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnY_RaizdeXActionPerformed(evt);
            }
        });

        BtnXalCubo.setText("x^3");
        BtnXalCubo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnXalCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXalCuboActionPerformed(evt);
            }
        });

        BtnNum4.setText("4");
        BtnNum4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum4ActionPerformed(evt);
            }
        });

        BtnNum5.setText("5");
        BtnNum5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum5ActionPerformed(evt);
            }
        });

        BtnNum6.setText("6");
        BtnNum6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum6ActionPerformed(evt);
            }
        });

        BtnMultiplicar.setText("x");
        BtnMultiplicar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplicarActionPerformed(evt);
            }
        });

        Btn1entreX.setText("1/x");
        Btn1entreX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Btn1entreX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1entreXActionPerformed(evt);
            }
        });

        BtnRestar.setText("-");
        BtnRestar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarActionPerformed(evt);
            }
        });

        BtnNum3.setText("3");
        BtnNum3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum3ActionPerformed(evt);
            }
        });

        BtnNum2.setText("2");
        BtnNum2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum2ActionPerformed(evt);
            }
        });

        BtnNum1.setText("1");
        BtnNum1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum1ActionPerformed(evt);
            }
        });

        BtnXalCuadrado.setText("x^2");
        BtnXalCuadrado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnXalCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXalCuadradoActionPerformed(evt);
            }
        });

        BtnRaizCubica.setText("3√x");
        BtnRaizCubica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnRaizCubica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRaizCubicaActionPerformed(evt);
            }
        });

        BtnFactorial.setText("n!");
        BtnFactorial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFactorialActionPerformed(evt);
            }
        });

        Btn10a_laX.setText("10^x");
        Btn10a_laX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Btn10a_laX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn10a_laXActionPerformed(evt);
            }
        });

        BtnEXP.setText("EXP");
        BtnEXP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnEXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEXPActionPerformed(evt);
            }
        });

        BtnLogaritmo.setText("log");
        BtnLogaritmo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnLogaritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogaritmoActionPerformed(evt);
            }
        });

        BtnNum0.setText("0");
        BtnNum0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum0ActionPerformed(evt);
            }
        });

        BtnPuntoDecimal.setText(".");
        BtnPuntoDecimal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnPuntoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPuntoDecimalActionPerformed(evt);
            }
        });

        BtnSumar.setText("+");
        BtnSumar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumarActionPerformed(evt);
            }
        });

        BtnIgual.setText("=");
        BtnIgual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMmas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCosmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSenmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTanmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnXaMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BntXmenosY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSlash, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnEuler, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnY_RaizdeX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnXalCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn1entreX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn10a_laX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnEXP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnLogaritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnNum0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRaizCubica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnXalCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnPuntoDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMmas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCosmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSenmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTanmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnXaMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntXmenosY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSlash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEuler, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnY_RaizdeX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnXalCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn1entreX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRaizCubica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnXalCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn10a_laX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEXP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLogaritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnPuntoDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BtnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 240));

        getContentPane().add(ComboxFuncionesPredeterminadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 120, 30));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("Predeterminadas:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Funciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonRadianesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonRadianesActionPerformed

    private void BtnSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSenoActionPerformed

    private void BtnTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTangenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTangenteActionPerformed

    private void BtnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMCActionPerformed

    private void BtnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMRActionPerformed

    private void BtnMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMSActionPerformed

    private void BtnMmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMmasActionPerformed

    private void BtnMmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMmenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMmenosActionPerformed

    private void BtnSenmenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSenmenos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSenmenos1ActionPerformed

    private void BtnTanmenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTanmenos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTanmenos1ActionPerformed

    private void BtnBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackSpaceActionPerformed

    private void BtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCEActionPerformed

    private void BtnMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMasMenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMasMenosActionPerformed

    private void BtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRaizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRaizActionPerformed

    private void BtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCActionPerformed

    private void BtnXaMenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXaMenos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnXaMenos1ActionPerformed

    private void BntXmenosYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntXmenosYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BntXmenosYActionPerformed

    private void BtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum7ActionPerformed

    private void BtnSlashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSlashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSlashActionPerformed

    private void BtnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPorcentajeActionPerformed

    private void BtnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPiActionPerformed

    private void BtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum8ActionPerformed

    private void BtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum9ActionPerformed

    private void BtnEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEulerActionPerformed

    private void BtnY_RaizdeXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnY_RaizdeXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnY_RaizdeXActionPerformed

    private void BtnXalCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXalCuboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnXalCuboActionPerformed

    private void BtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum4ActionPerformed

    private void BtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum5ActionPerformed

    private void BtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum6ActionPerformed

    private void BtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMultiplicarActionPerformed

    private void Btn1entreXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1entreXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1entreXActionPerformed

    private void BtnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRestarActionPerformed

    private void BtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum3ActionPerformed

    private void BtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum2ActionPerformed

    private void BtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum1ActionPerformed

    private void BtnXalCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXalCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnXalCuadradoActionPerformed

    private void BtnRaizCubicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRaizCubicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRaizCubicaActionPerformed

    private void BtnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFactorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnFactorialActionPerformed

    private void Btn10a_laXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn10a_laXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn10a_laXActionPerformed

    private void BtnEXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEXPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEXPActionPerformed

    private void BtnLogaritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogaritmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLogaritmoActionPerformed

    private void BtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNum0ActionPerformed

    private void BtnPuntoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPuntoDecimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPuntoDecimalActionPerformed

    private void BtnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSumarActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntXmenosY;
    private javax.swing.JButton Btn10a_laX;
    private javax.swing.JButton Btn1entreX;
    private javax.swing.JButton BtnBackSpace;
    private javax.swing.JButton BtnC;
    private javax.swing.JButton BtnCE;
    private javax.swing.JButton BtnCoseno;
    private javax.swing.JButton BtnCosmenos1;
    private javax.swing.JButton BtnEXP;
    private javax.swing.JButton BtnEuler;
    private javax.swing.JButton BtnFactorial;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnLogaritmo;
    private javax.swing.JButton BtnMC;
    private javax.swing.JButton BtnMR;
    private javax.swing.JButton BtnMS;
    private javax.swing.JButton BtnMasMenos;
    private javax.swing.JButton BtnMmas;
    private javax.swing.JButton BtnMmenos;
    private javax.swing.JButton BtnMultiplicar;
    private javax.swing.JButton BtnNum0;
    private javax.swing.JButton BtnNum1;
    private javax.swing.JButton BtnNum2;
    private javax.swing.JButton BtnNum3;
    private javax.swing.JButton BtnNum4;
    private javax.swing.JButton BtnNum5;
    private javax.swing.JButton BtnNum6;
    private javax.swing.JButton BtnNum7;
    private javax.swing.JButton BtnNum8;
    private javax.swing.JButton BtnNum9;
    private javax.swing.JButton BtnPi;
    private javax.swing.JButton BtnPorcentaje;
    private javax.swing.JButton BtnPuntoDecimal;
    private javax.swing.JButton BtnRaiz;
    private javax.swing.JButton BtnRaizCubica;
    private javax.swing.JButton BtnRestar;
    private javax.swing.JButton BtnSenmenos1;
    private javax.swing.JButton BtnSeno;
    private javax.swing.JButton BtnSlash;
    private javax.swing.JButton BtnSumar;
    private javax.swing.JButton BtnTangente;
    private javax.swing.JButton BtnTanmenos1;
    private javax.swing.JButton BtnXaMenos1;
    private javax.swing.JButton BtnXalCuadrado;
    private javax.swing.JButton BtnXalCubo;
    private javax.swing.JButton BtnY_RaizdeX;
    private javax.swing.JComboBox<String> ComboxFuncionesPredeterminadas;
    private javax.swing.JRadioButton RadioButtonRadianes;
    private javax.swing.JRadioButton RadioButtonRadianes1;
    private javax.swing.JTextField TxtNum1;
    private javax.swing.JTextField TxtNum2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
