/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import FactoryMethod.FormulaAccion;
import FactoryMethod.FormulaCreator;
import FactoryMethod.FormulaRegistry;
import Strategy.EvaluadorGeneralStrategy;
import Strategy.OperacionContexto;
import javax.swing.JOptionPane;


/**
 *
 * @author LENOVO
 */
public class GUI extends javax.swing.JFrame {
    //Variables de estado
    private double primerNumero = 0;
    private String operacion = "";
    private boolean esperandoNuevoNumero = false;
    OperacionContexto contexto = new OperacionContexto();
    
    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(255,255,255));
        jPanel1.setBackground(new java.awt.Color(255,255,255));
        
        try {
            Class.forName("FactoryMethod.PitagorasFormulaCreator");
            Class.forName("FactoryMethod.TaylorFormulaCreator");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        
        for (String nombre : FormulaRegistry.listarFormulas()) {
            ComboxFuncionesPredeterminadas.addItem(nombre); 
        }
        
//        ComboxFuncionesPredeterminadas.addItem(new TaylorFormulaCreator());
//        ComboxFuncionesPredeterminadas.addItem(new PitagorasFormulaCreator());
        CajaNumero2.setText("0");
    }
    
    private void agregarALaCaja(String txt){
        String actual = CajaNumero2.getText(); 
        CajaNumero2.setText(actual + txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        CajaNumero2 = new javax.swing.JTextField();
        RadioButtonRadianes = new javax.swing.JRadioButton();
        RadioButtonRadianes1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        BtnCoseno = new javax.swing.JButton();
        BtnSeno = new javax.swing.JButton();
        BtnTangente = new javax.swing.JButton();
        BtnMC = new javax.swing.JButton();
        BtnMR = new javax.swing.JButton();
        BtnMS = new javax.swing.JButton();
        BtnMmas = new javax.swing.JButton();
        BtnMmenos = new javax.swing.JButton();
        BtnCosmenos1 = new javax.swing.JButton();
        BtnSenmenos1 = new javax.swing.JButton();
        BtnTanmenos1 = new javax.swing.JButton();
        BtnCE = new javax.swing.JButton();
        BtnC = new javax.swing.JButton();
        BtnPi = new javax.swing.JButton();
        BtnXaMenos1 = new javax.swing.JButton();
        BntXmenosY = new javax.swing.JButton();
        BtnNum7 = new javax.swing.JButton();
        BtnDivision = new javax.swing.JButton();
        BtnPorcentaje = new javax.swing.JButton();
        BtnNum8 = new javax.swing.JButton();
        BtnNum9 = new javax.swing.JButton();
        BtnEuler = new javax.swing.JButton();
        BtnY_RaizdeX = new javax.swing.JButton();
        BtnXalCubo = new javax.swing.JButton();
        BtnNum4 = new javax.swing.JButton();
        BtnNum5 = new javax.swing.JButton();
        BtnNum6 = new javax.swing.JButton();
        BtnMultiplicar = new javax.swing.JButton();
        Btn1entreX = new javax.swing.JButton();
        BtnRestar = new javax.swing.JButton();
        BtnNum3 = new javax.swing.JButton();
        BtnNum2 = new javax.swing.JButton();
        BtnNum1 = new javax.swing.JButton();
        BtnXalCuadrado = new javax.swing.JButton();
        BtnRaizCubica = new javax.swing.JButton();
        BtnFactorial = new javax.swing.JButton();
        Btn10a_laX = new javax.swing.JButton();
        BtnEXP = new javax.swing.JButton();
        BtnLogaritmo = new javax.swing.JButton();
        BtnNum0 = new javax.swing.JButton();
        BtnPuntoDecimal = new javax.swing.JButton();
        BtnSumar = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnIgual1 = new javax.swing.JButton();
        BtnIgual2 = new javax.swing.JButton();
        BtnBackSpace = new javax.swing.JButton();
        BtnRaiz = new javax.swing.JButton();
        ComboxFuncionesPredeterminadas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BDJ Quantum");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(20, 20, 20, 20));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("JFramePrincipal"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CajaNumero2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CajaNumero2.setText("0");
        CajaNumero2.setBorder(null);
        CajaNumero2.setMargin(new java.awt.Insets(10, 10, 10, 10));
        CajaNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaNumero2ActionPerformed(evt);
            }
        });
        getContentPane().add(CajaNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 500, 50));

        RadioButtonRadianes.setText("Sexagesimales");
        RadioButtonRadianes.setBorder(null);
        RadioButtonRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonRadianesActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButtonRadianes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        RadioButtonRadianes1.setText("Radianes");
        RadioButtonRadianes1.setBorder(null);
        getContentPane().add(RadioButtonRadianes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        BtnCoseno.setText("cos");
        BtnCoseno.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnSeno.setText("sen");
        BtnSeno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSenoActionPerformed(evt);
            }
        });

        BtnTangente.setText("tan");
        BtnTangente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTangenteActionPerformed(evt);
            }
        });

        BtnMC.setText("MC");
        BtnMC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMCActionPerformed(evt);
            }
        });

        BtnMR.setText("MR");
        BtnMR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMRActionPerformed(evt);
            }
        });

        BtnMS.setText("MS");
        BtnMS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMSActionPerformed(evt);
            }
        });

        BtnMmas.setText("M+");
        BtnMmas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMmasActionPerformed(evt);
            }
        });

        BtnMmenos.setText("M-");
        BtnMmenos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMmenosActionPerformed(evt);
            }
        });

        BtnCosmenos1.setText("cos-1");
        BtnCosmenos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnSenmenos1.setText("sen-1");
        BtnSenmenos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnSenmenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSenmenos1ActionPerformed(evt);
            }
        });

        BtnTanmenos1.setText("tan-1");
        BtnTanmenos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnTanmenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTanmenos1ActionPerformed(evt);
            }
        });

        BtnCE.setForeground(new java.awt.Color(255, 102, 51));
        BtnCE.setText("CE");
        BtnCE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCEActionPerformed(evt);
            }
        });

        BtnC.setForeground(new java.awt.Color(255, 102, 51));
        BtnC.setText("C");
        BtnC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCActionPerformed(evt);
            }
        });

        BtnPi.setText("π");
        BtnPi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPiActionPerformed(evt);
            }
        });

        BtnXaMenos1.setText("x^-1");
        BtnXaMenos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnXaMenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXaMenos1ActionPerformed(evt);
            }
        });

        BntXmenosY.setText("x^y");
        BntXmenosY.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BntXmenosY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntXmenosYActionPerformed(evt);
            }
        });

        BtnNum7.setText("7");
        BtnNum7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum7ActionPerformed(evt);
            }
        });

        BtnDivision.setText("÷");
        BtnDivision.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDivisionActionPerformed(evt);
            }
        });

        BtnPorcentaje.setText("%");
        BtnPorcentaje.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPorcentajeActionPerformed(evt);
            }
        });

        BtnNum8.setText("8");
        BtnNum8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum8ActionPerformed(evt);
            }
        });

        BtnNum9.setText("9");
        BtnNum9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum9ActionPerformed(evt);
            }
        });

        BtnEuler.setText("e");
        BtnEuler.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEulerActionPerformed(evt);
            }
        });

        BtnY_RaizdeX.setText("y√x");
        BtnY_RaizdeX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnY_RaizdeX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnY_RaizdeXActionPerformed(evt);
            }
        });

        BtnXalCubo.setText("x^3");
        BtnXalCubo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnXalCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXalCuboActionPerformed(evt);
            }
        });

        BtnNum4.setText("4");
        BtnNum4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum4ActionPerformed(evt);
            }
        });

        BtnNum5.setText("5");
        BtnNum5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum5ActionPerformed(evt);
            }
        });

        BtnNum6.setText("6");
        BtnNum6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum6ActionPerformed(evt);
            }
        });

        BtnMultiplicar.setText("x");
        BtnMultiplicar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplicarActionPerformed(evt);
            }
        });

        Btn1entreX.setText("1/x");
        Btn1entreX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Btn1entreX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1entreXActionPerformed(evt);
            }
        });

        BtnRestar.setText("-");
        BtnRestar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarActionPerformed(evt);
            }
        });

        BtnNum3.setText("3");
        BtnNum3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum3ActionPerformed(evt);
            }
        });

        BtnNum2.setText("2");
        BtnNum2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum2ActionPerformed(evt);
            }
        });

        BtnNum1.setText("1");
        BtnNum1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum1ActionPerformed(evt);
            }
        });

        BtnXalCuadrado.setText("x^2");
        BtnXalCuadrado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnXalCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXalCuadradoActionPerformed(evt);
            }
        });

        BtnRaizCubica.setText("3√x");
        BtnRaizCubica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnRaizCubica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRaizCubicaActionPerformed(evt);
            }
        });

        BtnFactorial.setText("n!");
        BtnFactorial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFactorialActionPerformed(evt);
            }
        });

        Btn10a_laX.setText("10^x");
        Btn10a_laX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Btn10a_laX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn10a_laXActionPerformed(evt);
            }
        });

        BtnEXP.setText("EXP");
        BtnEXP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnEXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEXPActionPerformed(evt);
            }
        });

        BtnLogaritmo.setText("log");
        BtnLogaritmo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnLogaritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogaritmoActionPerformed(evt);
            }
        });

        BtnNum0.setText("0");
        BtnNum0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNum0ActionPerformed(evt);
            }
        });

        BtnPuntoDecimal.setText(".");
        BtnPuntoDecimal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnPuntoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPuntoDecimalActionPerformed(evt);
            }
        });

        BtnSumar.setText("+");
        BtnSumar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumarActionPerformed(evt);
            }
        });

        BtnIgual.setText("=");
        BtnIgual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnIgual1.setText("∫");
        BtnIgual1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnIgual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgual1ActionPerformed(evt);
            }
        });

        BtnIgual2.setText("d/dx");
        BtnIgual2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnIgual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgual2ActionPerformed(evt);
            }
        });

        BtnBackSpace.setText("⌫");
        BtnBackSpace.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackSpaceActionPerformed(evt);
            }
        });

        BtnRaiz.setText("√");
        BtnRaiz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRaizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnXaMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BntXmenosY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnCosmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnSenmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnTanmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnBackSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnMmas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnMmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnIgual1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnEuler, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnY_RaizdeX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnXalCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn1entreX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Btn10a_laX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnEXP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnLogaritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnNum0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnRaizCubica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnXalCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnPuntoDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnIgual2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMmas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCosmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSenmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTanmenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnXaMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BntXmenosY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BtnIgual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEuler, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnY_RaizdeX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnXalCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn1entreX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnRaizCubica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnXalCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn10a_laX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnEXP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnLogaritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnPuntoDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BtnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(BtnIgual2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 530, 250));

        ComboxFuncionesPredeterminadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxFuncionesPredeterminadasActionPerformed(evt);
            }
        });
        getContentPane().add(ComboxFuncionesPredeterminadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 120, 30));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("Predeterminadas:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Funciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton de calculadora en radianes
    private void RadioButtonRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonRadianesActionPerformed
        
    }//GEN-LAST:event_RadioButtonRadianesActionPerformed

    //Boton para seno
    private void BtnSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSenoActionPerformed

    //Boton para tangente
    private void BtnTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTangenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTangenteActionPerformed

    //Boton para MCA
    private void BtnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMCActionPerformed

    //Boton MRA
    private void BtnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMRActionPerformed

    //Boton para MSA
    private void BtnMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMSActionPerformed

    //Boton de M+
    private void BtnMmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMmasActionPerformed

    //Boton de M-
    private void BtnMmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMmenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMmenosActionPerformed

    //Boton para seno a la -1
    private void BtnSenmenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSenmenos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSenmenos1ActionPerformed

    //Boton para tangente a la -1
    private void BtnTanmenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTanmenos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTanmenos1ActionPerformed

    //Boton para borrar ultimo digito
    private void BtnBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackSpaceActionPerformed
        String actual =  CajaNumero2.getText();
        if (actual.length() > 1) {
            CajaNumero2.setText(actual.substring(0, actual.length() - 1));   
        } else {
            CajaNumero2.setText("0");
            esperandoNuevoNumero = true;
        }
    }//GEN-LAST:event_BtnBackSpaceActionPerformed

    //Boton para CE
    private void BtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCEActionPerformed
        CajaNumero2.setText("");
        esperandoNuevoNumero = true;
    }//GEN-LAST:event_BtnCEActionPerformed

    //Boton para raiz
    private void BtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRaizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRaizActionPerformed

    //Boton para CA
    private void BtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCActionPerformed
        primerNumero = 0;
        operacion = "";
        esperandoNuevoNumero = false;
        CajaNumero2.setText("0");
    }//GEN-LAST:event_BtnCActionPerformed

    //Boton para X a la -1
    private void BtnXaMenos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXaMenos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnXaMenos1ActionPerformed

    //Boton de X a la -Y
    private void BntXmenosYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntXmenosYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BntXmenosYActionPerformed

    //Boton para numero 7
    private void BtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum7ActionPerformed
        agregarALaCaja("7");
    }//GEN-LAST:event_BtnNum7ActionPerformed

    //Boton de division
    private void BtnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivisionActionPerformed
        agregarALaCaja("/"); 
//        primerNumero = Double.parseDouble(CajaNumero2.getText());
//        operacion = "/";
//        CajaNumero1.setText(CajaNumero2.getText() + " /");
//        esperandoNuevoNumero = true;
    }//GEN-LAST:event_BtnDivisionActionPerformed
    
    //Boton porcentaje
    private void BtnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPorcentajeActionPerformed

    //Boton numero pi
    private void BtnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPiActionPerformed
        agregarALaCaja("Pi"); 
//        CajaNumero2.setText(String.valueOf(Math.PI));
//        esperandoNuevoNumero = true;
    }//GEN-LAST:event_BtnPiActionPerformed

    //Boton numero 8
    private void BtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum8ActionPerformed
        agregarALaCaja("8");
    }//GEN-LAST:event_BtnNum8ActionPerformed

    //Boton numero 9
    private void BtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum9ActionPerformed
        agregarALaCaja("9");
    }//GEN-LAST:event_BtnNum9ActionPerformed

    //Boton numero euler
    private void BtnEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEulerActionPerformed
        CajaNumero2.setText(String.valueOf(Math.E));
        esperandoNuevoNumero = true;
    }//GEN-LAST:event_BtnEulerActionPerformed

    //Boton Y raiz de X
    private void BtnY_RaizdeXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnY_RaizdeXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnY_RaizdeXActionPerformed

    //Boton X al cubo 
    private void BtnXalCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXalCuboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnXalCuboActionPerformed

    //Boton numero 4
    private void BtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum4ActionPerformed
        agregarALaCaja("4");
    }//GEN-LAST:event_BtnNum4ActionPerformed

    //Boton numero 5
    private void BtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum5ActionPerformed
        agregarALaCaja("5");
    }//GEN-LAST:event_BtnNum5ActionPerformed
    
    //Boton numero 6
    private void BtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum6ActionPerformed
        agregarALaCaja("6");
    }//GEN-LAST:event_BtnNum6ActionPerformed

    //Boton de multiplicacion
    private void BtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplicarActionPerformed
        agregarALaCaja("*");
//        primerNumero = Double.parseDouble(CajaNumero2.getText());
//        operacion = "x";
//        CajaNumero1.setText(CajaNumero2.getText() + " x");
//        esperandoNuevoNumero = true;
    }//GEN-LAST:event_BtnMultiplicarActionPerformed

    //Boton de 1 entre X
    private void Btn1entreXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1entreXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1entreXActionPerformed
    
    //Boton para restar
    private void BtnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarActionPerformed
        agregarALaCaja("-");
//        primerNumero = Double.parseDouble(CajaNumero2.getText());
//        operacion = "-";
//        CajaNumero1.setText(CajaNumero2.getText() + " -");
//        esperandoNuevoNumero = true;
    }//GEN-LAST:event_BtnRestarActionPerformed
    
    //Boton numero 3
    private void BtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum3ActionPerformed
        agregarALaCaja("3");
    }//GEN-LAST:event_BtnNum3ActionPerformed

    //Boton numero 2
    private void BtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum2ActionPerformed
        agregarALaCaja("2"); 
    }//GEN-LAST:event_BtnNum2ActionPerformed
    
    //Boton de numero 1
    private void BtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum1ActionPerformed
        agregarALaCaja("1"); 
    }//GEN-LAST:event_BtnNum1ActionPerformed

    //Boton de X al cuadrado
    private void BtnXalCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXalCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnXalCuadradoActionPerformed

    //Boton de raiz cubica
    private void BtnRaizCubicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRaizCubicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRaizCubicaActionPerformed
    
    //Boton de facotrial
    private void BtnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFactorialActionPerformed
//        int valor = Integer.parseInt(CajaNumero2.getText());
//        if (valor < 0) {
//            CajaNumero2.setText("Syntax Error");
//        } else {
//            long resultado = 1;
//            for (int i = 1; i <= valor; i++) {
//                resultado *= i;
//            }
//            CajaNumero2.setText(String.valueOf(resultado));
//        }
//        esperandoNuevoNumero = true;
    }//GEN-LAST:event_BtnFactorialActionPerformed

    //Boton de 10 a la X
    private void Btn10a_laXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn10a_laXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn10a_laXActionPerformed
    
    //Boton EXPA
    private void BtnEXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEXPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEXPActionPerformed

    //Boton de logaritmo
    private void BtnLogaritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogaritmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLogaritmoActionPerformed

    //Boton de numero 0
    private void BtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNum0ActionPerformed
        agregarALaCaja("0");
    }//GEN-LAST:event_BtnNum0ActionPerformed

    //Boton de punto decimal
    private void BtnPuntoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPuntoDecimalActionPerformed
        String actual = CajaNumero2.getText();
        if (!actual.contains(".")) {
            if (esperandoNuevoNumero) {
                CajaNumero2.setText("0.");
                esperandoNuevoNumero = false;
            } else {
                CajaNumero2.setText(actual + ".");
            }
        }
    }//GEN-LAST:event_BtnPuntoDecimalActionPerformed

    //Boton para sumar
    private void BtnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumarActionPerformed
        agregarALaCaja("+");
//        primerNumero = Double.parseDouble(CajaNumero2.getText());
//        operacion = "+";
//        CajaNumero1.setText(CajaNumero2.getText() + " + ");
//        esperandoNuevoNumero = true;
    }//GEN-LAST:event_BtnSumarActionPerformed
    
    //Boton de igual
    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        // antes de que resuelva, hay que poner aqui para que guarde esa operacion en la base de datos
        contexto.setEstrategia(new EvaluadorGeneralStrategy());
        String resultado = contexto.resolver(CajaNumero2.getText());
        CajaNumero2.setText(resultado); 
        
//        double segundoNumero = Double.parseDouble(CajaNumero2.getText());
//        double resultado = 0;
//        switch (operacion) {
//            case "+": 
//                resultado = primerNumero + segundoNumero;
//                break;
//            case "-":
//                resultado = primerNumero - segundoNumero;
//                break;
//            case "x":
//                resultado = primerNumero * segundoNumero;
//                break;
//            case "/":
//                if (segundoNumero == 0) {
//                    CajaNumero2.setText("Syntax Error");
//                    CajaNumero1.setText("");
//                    esperandoNuevoNumero = true;
//                    return;
//                } else {
//                    resultado = primerNumero / segundoNumero;
//                }
//                break;
//            default:
//                return;
//        }
//        CajaNumero2.setText(String.valueOf(resultado));
//        CajaNumero1.setText("");
//        esperandoNuevoNumero = true;
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnIgual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgual1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIgual1ActionPerformed

    private void BtnIgual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgual2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIgual2ActionPerformed

    private void ComboxFuncionesPredeterminadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxFuncionesPredeterminadasActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) ComboxFuncionesPredeterminadas.getSelectedItem();
        FormulaCreator creador = FormulaRegistry.obtenerCreador(seleccion);
        if (creador != null) {
            FormulaAccion formula = creador.crearFormula();
            CajaNumero2.setText(formula.getExpresion());
        } else {
            JOptionPane.showMessageDialog(null,"Formula no encontrada");
        }
//        FormulaCreator creator = (FormulaCreator) ComboxFuncionesPredeterminadas.getSelectedItem();
//        FormulaAccion formula = creator.crearFormula();
//        
//        TxtNum2.setText(formula.getExpresion());
    }//GEN-LAST:event_ComboxFuncionesPredeterminadasActionPerformed

    private void CajaNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaNumero2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntXmenosY;
    private javax.swing.JButton Btn10a_laX;
    private javax.swing.JButton Btn1entreX;
    private javax.swing.JButton BtnBackSpace;
    private javax.swing.JButton BtnC;
    private javax.swing.JButton BtnCE;
    private javax.swing.JButton BtnCoseno;
    private javax.swing.JButton BtnCosmenos1;
    private javax.swing.JButton BtnDivision;
    private javax.swing.JButton BtnEXP;
    private javax.swing.JButton BtnEuler;
    private javax.swing.JButton BtnFactorial;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnIgual1;
    private javax.swing.JButton BtnIgual2;
    private javax.swing.JButton BtnLogaritmo;
    private javax.swing.JButton BtnMC;
    private javax.swing.JButton BtnMR;
    private javax.swing.JButton BtnMS;
    private javax.swing.JButton BtnMmas;
    private javax.swing.JButton BtnMmenos;
    private javax.swing.JButton BtnMultiplicar;
    private javax.swing.JButton BtnNum0;
    private javax.swing.JButton BtnNum1;
    private javax.swing.JButton BtnNum2;
    private javax.swing.JButton BtnNum3;
    private javax.swing.JButton BtnNum4;
    private javax.swing.JButton BtnNum5;
    private javax.swing.JButton BtnNum6;
    private javax.swing.JButton BtnNum7;
    private javax.swing.JButton BtnNum8;
    private javax.swing.JButton BtnNum9;
    private javax.swing.JButton BtnPi;
    private javax.swing.JButton BtnPorcentaje;
    private javax.swing.JButton BtnPuntoDecimal;
    private javax.swing.JButton BtnRaiz;
    private javax.swing.JButton BtnRaizCubica;
    private javax.swing.JButton BtnRestar;
    private javax.swing.JButton BtnSenmenos1;
    private javax.swing.JButton BtnSeno;
    private javax.swing.JButton BtnSumar;
    private javax.swing.JButton BtnTangente;
    private javax.swing.JButton BtnTanmenos1;
    private javax.swing.JButton BtnXaMenos1;
    private javax.swing.JButton BtnXalCuadrado;
    private javax.swing.JButton BtnXalCubo;
    private javax.swing.JButton BtnY_RaizdeX;
    private javax.swing.JTextField CajaNumero2;
    private javax.swing.JComboBox<String> ComboxFuncionesPredeterminadas;
    private javax.swing.JRadioButton RadioButtonRadianes;
    private javax.swing.JRadioButton RadioButtonRadianes1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
